### ISSUE TITLE
Feature to recognize special keys and shortcuts (plugin compatibility)

### ISSUE THREAD

**Issue by BenjaminGalliot** [jdlien/Kaleidoscope-LEDEffect-FunctionalColor#2]
Hello,

The system does not recognize the special keys, like `M()` (from _Macros_), `OSL()`, `OSM()` (from _OneShot_), `RALT_T()` (from _QuKeys_), etc.

The only workaround I found was to configure all other key groups (modifying some and adding some others like International keys) and giving the default color to them. 

Thank you for your great work, anyway.

Cheers.

**Comment by jdlien** [comment]
Thanks for the feedback.
You should be able to specify *any* key at all if you make a colorlist and add it in there. You can see the example.ino that does this with macro keys for controlling the brightness of the lights.

FC_START_COLOR_LIST(customColors)
 // This shows how you can set the color of custom macros
 FC_GROUPKEY(M(MACRO_FCUP))
 FC_KEYCOLOR(M(MACRO_FCDOWN), cyan)
FC_END_COLOR_LIST

Remember that when you use a Colorlist in this way you have to specify it as an argument when instantiating your FunctionalColor theme:
FCPlugin funColor(FC_COLOR_LIST(customColors));

I think this *should* work, although I haven't tested it with special keys from other plugins and stuff, but they all should resolve to a key struct in the same way and just work... you can't use the colorMap structs to affect these types of keys, but note that you can use colorLists with colorMap structs (custom or built-in themes), and the colorList should override the colorMap colors.

I hope this helps and that you're able to find a way to get this to work with your setup.
