### ISSUE TITLE
Compatibility with most recent firmware?

### ISSUE THREAD

**Issue by lgnakano** [jdlien/Kaleidoscope-LEDEffect-FunctionalColor#4]
I must be doing something wrong. I cannot get the samples to compile (error on void LEDFunctionalColor::FCPlugin::update(void). ::Layer not defined).

Am I the only one with this issue?

**Comment by jdlien** [comment]
Do you only have one layer defined?
I have never tested this plug-in with that configuration and it sounds like that’s causing an issue.

You could create a secondary “transparent” layer (that is exactly the same as the first) which should solve this problem… Someday when I actually work on this again I could probably fix this properly.

**Comment by lgnakano** [comment]
I am actually trying to compile the sample code, which has three layers.

I had to make changes to use KALEIDOSCOPE_INIT_PLUGINS instead of Kaleidoscope.use (which required use of the variables, instead of address (&) of the variables.

It looks like there were changes made to layers on the 1.94.0-beta or before. I would like to know which version you used before, and maybe I can figure out how to fix that.

I tried to just comment the code that was not compiling, and see how far it took me, but I end up with these errors:

sketch\fcexample.ino.cpp.o: In function `cRGB kaleidoscope::LEDFunctionalColor::groupColorLookup<kaleidoscope::LEDFunctionalColor::colorMapDefault>(kaleidoscope::Key const&, bool&)':

D:\Users\Nakano\Documents\fcexample/fcexample.ino:414: undefined reference to `kaleidoscope::LEDFunctionalColor::colorMapDefault::control'

It looks like it may be related to namespaces. I am not new to c++, but I am a novice on Arduino, so I am still trying to figure out where the libraries go and how Arduino decides which libraries come from where.

**Comment by ycros** [comment]
I had the same two sets of errors, and eventually I managed to get it to compile and work.

The changes I made are here (these will only work with the default colormap and are a quick and dirty hack): https://github.com/ycros/Kaleidoscope-LEDEffect-FunctionalColor/commit/3158f5ea2a581352b45d4fe1ee0386580fb921b5 

The two things I had to change were to add definitions for every single one of the `colorMap` struct members, and removing the `::` in front of the `Layer_` in the `update()` method. I'm not sure about the latter, but from my limited understanding/googling you don't need extra definitions `static constexpr` definitions as of C++17 so my guess is that this is a compiler/toolchain version issue. I'm using the stock standard Arduino IDE install from arduino.cc so the compiler I end up using is `gcc version 5.4.0 (GCC)`.

**Comment by jdlien** [comment]
Thank you for looking into this. Unfortunately I don't use Keyboardio at the moment and I'm pretty busy with work and school, so I haven't had much time to look into this. Some day I will get this running better! Please feel free to submit a pull request if you think you can solve any issues with this plugin.

**Comment by fluffy-critter** [comment]
I'd also love to see this plugin be updated for the current Kaleidoscope API. @algernon suggested that he'd be willing to do the work to submit a PR although it looks like @ycros already did much of what's necessary to update it.

**Comment by noseglasses** [comment]
After a PR has been merged that restores compatibility with the v2 plugin API, this plugin is now supposed to work again with the current firmware. Please give it a try and report back any problems/errors.

**Comment by lgnakano** [comment]
I am not sure I have something wrong on my arduino configuration, but I was still getting the errors that I saw before regarding undefined references to colorMapDefault.  Once I applied the changes that @lycros made, things worked fine for colorMapDefault, and I was able to use for my purposes.  When I have some copious free time (ha!), I intend to see if I can make changes for the other colorMaps, and possibly change the examples so they work properly. If/when I get to that stage, I will place a PR to get the changes incorporated into the tree as well.

**Comment by noseglasses** [comment]
There's an ongoing discussion about build problems here: https://github.com/jdlien/Kaleidoscope-LEDEffect-FunctionalColor/pull/5

@lgnakano,are your problems somehow related?

**Comment by noseglasses** [comment]
This issue can probably be closed after https://github.com/jdlien/Kaleidoscope-LEDEffect-FunctionalColor/pull/8 has been merged.

**Comment by jdlien** [comment]
Latest version supports current firmware.
