### ISSUE TITLE
Documentation and second example sketch out of data

### ISSUE THREAD

**Issue by noseglasses** [jdlien/Kaleidoscope-LEDEffect-FunctionalColor#9]
The plugin does now work with firmware v2.

https://github.com/jdlien/Kaleidoscope-LEDEffect-FunctionalColor/pull/8 introduced some macros that still need to be documented. After this PR, the example sketch `fc_example.ino` still needs to be updated in the same way as it has been done for `fc_example_simple.ino`.

**Comment by jdlien** [comment]
Example sketches now built and function correctly on latest firmware.
Readme documentation is up to date.

Please let me know if any errors, non-working code, or inaccuracies are found in the documentation or example sketches.
